In [1]:
import numpy as np

In [2]:
# PERCABANGAN
def kalkulator():
    try:
        angka1 = float(input("Masukkan angka 1\t: "))
        operator = input("Masukan operator\t: ")
        angka2 = float(input("Masukkan angka 2\t: "))

        if operator ==  ("x"):
            perkalian = angka1 * angka2
            print(f"Hasil perhitungan \t: {perkalian}")
        elif operator == (":"):
            pembagian = angka1 / angka2
            print(f"Hasil perhitungan \t: {pembagian}")
        elif operator == ("+"):
            penjumlahan = angka1 + angka2
            print(f"Hasil perhitungan \t: {penjumlahan}")
        elif operator == ("-"):
            pengurangan = angka1 - angka2
            print(f"Hasil perhitungan \t: {pengurangan}")
        elif operator == ("^"):
            pangkat = angka1 ** angka2
            print(f"Hasil perhitungan \t: {pangkat}")
        else:
            print("Operator operasi tidak tersedia")

        print("Anda berhasil melakukan perhitungan")

    except ValueError:
        print("Input tidak valid. Pastikan Anda memasukkan angka.")

In [3]:
def kalkulator():
    try:
        angka1 = float(input("Masukkan angka pertama: "))
        operasi = input("Masukkan operasi (+, -, x, :, ^): ")
        angka2 = float(input("Masukkan angka kedua: "))
        
        if operasi == '+':
            hasil = angka1 + angka2
        elif operasi == '-':
            hasil = angka1 - angka2
        elif operasi == 'x':
            hasil = angka1 * angka2
        elif operasi == ':':
            hasil = angka1 / angka2
        elif operasi == '^':
            hasil = angka1 ** angka2
        else:
            print("Operasi tidak valid.")
            return
        
        print(f"Hasil dari {angka1} {operasi} {angka2} = {hasil}")
        
    except ValueError:
        print("Input tidak valid. Pastikan Anda memasukkan angka.")

In [4]:
kalkulator()

Masukkan angka pertama:  2
Masukkan operasi (+, -, x, :, ^):  -
Masukkan angka kedua:  1


Hasil dari 2.0 - 1.0 = 1.0


In [5]:
c = np.array([1,2,3])
c[1]

2

In [6]:
c = np.array([(1,2,3), (4,5,6)])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
array_1 = np.arange(5)
array_1

array([0, 1, 2, 3, 4])

In [8]:
array_1[2::1]

array([2, 3, 4])

In [9]:
list_of_list = [[1,2,3], [4,5,6], [7,8,9]]
list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
list_of_list = np.array([[1,2,3], [4,5,6], [7,8,9]])
list_of_list.shape

(3, 3)

In [12]:
list_of_list2 = [[1, 2], [3, 4], [5,6]]
array_3 = np.array(list_of_list2 )
array_3.shape

# (baris, kolom)

(3, 2)

In [13]:
# ndim

list_of_list = np.array([[1,2,3], [4,5,6], [7,8,9]])


print(list_of_list.ndim)

2


## Creating Array

In [14]:
a = np.zeros([3,4])
print(a.ndim)

2


In [26]:
c = np.array([1,2,3,4,5,6,7,8,9])

print(c.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
array_4 = np.array([4,5,6])
array_4 = 
array_4.shape

(3,)

In [36]:
# np.expand_dims

array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7, axis=1)
print(array_8)
print(array_8.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)


In [37]:
array_9 = np.expand_dims(array_7, axis=0)
print(array_9)
print(array_9.shape)

[[3 4 5 6 7 8 9]]
(1, 7)


In [40]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7<=8])

[3 4 5 6 7 8]


In [43]:
array_11 = np.array([[3,5,7], [8,9,10], [-1,-2,-3]])
array_11.shape
print(array_11[array_11<5])

[ 3 -1 -2 -3]


### np.zeros()

In [15]:
np.zeros(4) #1D

array([0., 0., 0., 0.])

In [25]:
print(np.zeros([3,3])) #2D

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### np.ones()

In [17]:
np.ones(4) #1D

array([1., 1., 1., 1.])

In [18]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### np.empty()

In [19]:
np.empty([3,3]) #1D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.arange(4)

array([0, 1, 2, 3])

In [21]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [22]:
array1 = np.array([1,2,3])
np.append(array1, [10,11])

array([ 1,  2,  3, 10, 11])

In [23]:
array1 = np.array([1, 2, 3, 4, 5])
np.delete(array1, 2)

array([1, 2, 4, 5])

In [24]:
print(np.sort([9,1,4,5,6,2,11,7]))

[ 1  2  4  5  6  7  9 11]


In [44]:
row = int(input("Enter number of rows: "))

print("Generated Hourglass Pattern is: ")
for i in range(row, 0, -1):
    for j in range(row-i):
        print(" ", end="")
    for j in range(1, 2*i):
        print("*", end="")
    print()

# Lower-half
for i in range(2, row+1):
    for j in range(row-i):
        print(" ", end="")
    for j in range(1, 2*i):
        print("*", end="")
    print()


Enter number of rows:  4


Generated Hourglass Pattern is: 


TypeError: 'float' object cannot be interpreted as an integer

In [62]:
import math
rows = int(input("Enter number of rows: "))

if rows % 2 == 1:
    rows2 = rows / 2 
    math.floor(rows2)
k = 0

for i in range(rows2+1, 1, -1):
    for space in range(0, rows-i):
        print("  ", end="")
    for j in range(i, 2*i-1):
        print("* ", end="")
    for j in range(1, i-1):
        print("* ", end="")
    print()

for i in range(1, rows2+1):
    for space in range(1, (rows-i)+1):
        print(end="  ")
   
    while k!=(2*i-1):
        print("* ", end="")
        k += 1
    k = 0
    print()


SyntaxError: invalid syntax (169566059.py, line 3)

In [65]:

n = int(input("Masukkan tinggi bagian atas dan bawah (bilangan ganjil): "))
if n % 2 == 0:
    n -= 1
for i in range(n//2+1):
    for j in range(i):
        print(" ", end="")
    for k in range(n-2*i):
        if k % 2 == 0:
            print("*", end="")
        else:
            print(" ", end="")
    print()
for i in range(n//2, 0, -1):
    for j in range(i-1):
        print(" ", end="")
    for k in range(n-2*i+2):
        if k % 2 == 0:
            print("*", end="")
        else:
            print(" ", end="")
    print()

Masukkan tinggi bagian atas dan bawah (bilangan ganjil):  10


* * * * *
 * * * *
  * * *
   * *
    *
   * *
  * * *
 * * * *
* * * * *


In [68]:
a = np.array([1,2,3])
b = np.array([4,5,6])
# vertikal
print(np.vstack([a, b]))
# horizontal
print(np.hstack([a, b]))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [70]:
# hsplit
a = np.array([1,2,3,4,5,6])
array_split = np.hsplit(a, 2)
array_split

[array([1, 2, 3]), array([4, 5, 6])]

In [84]:
# merubah baris jadi kolom

print('\ntranspose matrix dari a:')
a = np.array([[1,2,3], [4,5,6]])
print(a)
print('shape a : ', a.shape, '\n')


print(a.transpose())
# atau
print('\n',np.transpose(a))
# atau
print('\n',a.T)

print('\nshape a transpose: ',a.T.shape)




transpose matrix dari a:
[[1 2 3]
 [4 5 6]]
shape a :  (2, 3) 

[[1 4]
 [2 5]
 [3 6]]

 [[1 4]
 [2 5]
 [3 6]]

 [[1 4]
 [2 5]
 [3 6]]

 shape a transpose:  (3, 2)


In [85]:
# flatten array -> menjadi vector baris
print('\nflatten matrix a : ')
print('\n',a.ravel()) 
# atau
print('\n',np.ravel(a))


flatten matrix a : 

 [1 2 3 4 5 6]

 [1 2 3 4 5 6]


In [91]:
print('\nresize matrix a:')
a = np.array([[1,2,3], [4,5,6]])
print(a.reshape(3,2))


resize matrix a:
[[1 2]
 [3 4]
 [5 6]]


In [92]:
a = np.array([[1,2,3], [4,5,6]])
np.sum(a)

21

In [94]:
a = np.array([[1,2,3], [4,5,6]])
np.square(a)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [95]:
b = np.array([[ 1,  4,  9], [16, 25, 36]])

np.sqrt(b)

array([[1., 2., 3.],
       [4., 5., 6.]])

In [103]:

batas_bawah = int(input('Masukka batas bawah :'))
batas_atas = int(input('Masukka batas atas :'))

for angka in range(batas_bawah, batas_atas + 1):
   if angka > 1:
       for i in range(2, angka):
           if (angka % i) == 0:
               break
       else:
           print(angka)

Masukka batas bawah : 11
Masukka batas atas : 30


11
13
17
19
23
29


In [104]:
def bil_prima(awal, akhir):
    prima = []
    for i in range(awal, akhir + 1):
        if i > 1:
            for j in range(2, i):
                if (i % j) == 0:
                    break
            else:
                prima.append(i)
    return prima
awal = int(input("Masukkan nilai awal : "))
akhir = int(input("Masukkan nilai akhir : "))
print(bil_prima(awal,akhir))

Masukkan nilai awal :  10
Masukkan nilai akhir :  30


[11, 13, 17, 19, 23, 29]
