In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [3]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [4]:
model.fit(x, y)

LogisticRegression(random_state=0, solver='liblinear')

In [5]:
model = LogisticRegression(solver='liblinear', random_state=0).fit(x, y)

In [6]:
model.classes_

array([0, 1])

In [12]:
# Model di atas memiliki binary class

In [7]:
print(model.intercept_, model.coef_)

[-1.04608067] [[0.51491375]]


In [13]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
model.predict_proba(x)

# medict proba adalah 

array([[0.74002157, 0.25997843],
       [0.62975524, 0.37024476],
       [0.5040632 , 0.4959368 ],
       [0.37785549, 0.62214451],
       [0.26628093, 0.73371907],
       [0.17821501, 0.82178499],
       [0.11472079, 0.88527921],
       [0.07186982, 0.92813018],
       [0.04422513, 0.95577487],
       [0.02690569, 0.97309431]])

In [9]:
model.predict(x)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1])

In [10]:
model.score(x, y)

0.9

In [11]:
confusion_matrix(y, model.predict(x))

array([[3, 1],
       [0, 6]], dtype=int64)

In [ ]:
y_pred = 

In [18]:
cm = confusion_matrix(y,y_pred)

fig, ax = plt.subplots(figsize=(8,8))
ax.imshow(cm)
ax.grid(False)
ax.xaxis.set(ticks=(0,1),ticklabels = ('Predicted 0s','Predicted 1s'))
ax.yaxis.set(ticks=(0,1),ticklabels = ('Actual 0s','Actual 1s'))
ax.set_ylim(1.5,-0.5)
for i in range(2):
    for j in range(2):
        ax.text(j,i,cm[i,j],ha='center',va='center',color='red')
plt.show()

NameError: name 'y_pred' is not defined

In [ ]:
TP = 6
FP = 1
FN = 0
TN = 3

acc = (TP+TN)/(TP+FP+TN+FN)
pre = (TP) / (TP+FP)
re = (TP) / (TP/FN)
f1 = (TP+TP) / (TP+TP+FP+FN)

print(acc)
print(pre)
print(re)
print(f1)

In [ ]:
print(classification_report(y, y_pred0))

In [19]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [20]:
x, y = load_digits(return_X_y=True)